export default {
  products: [
    {
      name: "Assortment of spices",
      category: "Spices",
      image: "images/asian-food1.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Spices in any quantity",
      category: "Chutneys",
      image: "images/asian-food3.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 4,
      numReviews: 8,
    },
    {
      name: "Assortment of spices",
      category: "Oils",
      image: "images/asian-food2.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 3.5,
      numReviews: 3,
    },
    {
      name: "Assortment of spices",
      category: "Spices",
      image: "images/asian-food4.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 4.5,
      numReviews: 14,
    },
    {
      name: "Assortment of rices",
      category: "Rice",
      image: "images/asian-food5.jpeg",
      price: 7,
      brand: "India's Finest",
      rating: 5,
      numReviews: 17,
    },
    {
      name: "Assortment of spices",
      category: "Spices",
      image: "images/asian-food2.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Assortment of spices",
      category: "Oils",
      image: "images/asian-food1.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 4.5,
      numReviews: 7,
    },
    {
      name: "Assortment of spices",
      category: "Flour",
      image: "images/asian-food4.jpeg",
      price: 37,
      brand: "India's Finest",
      rating: 5,
      numReviews: 6,
    },
    {
      name: "Assortment of rices",
      category: "Rice",
      image: "images/asian-food5.jpeg",
      price: 7,
      brand: "India's Finest",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
